version: 2
jobs:
  ensure-deps:
    docker:
      - image: ayankovsky/node-serverless-aws

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v1-yarn-{{ .Branch }}-
            - v1-yarn-

      - run:
          name: Install Dependencies
          command: yarn

      - save_cache:
          key: v1-yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - .cache/yarn

  dev-deploy:
    environment:
      PROJECT: cloudkeeper-metrics-service
    working_directory: ~/repo
    docker:
      - image: ayankovsky/node-serverless-aws
    steps:
      - checkout
      - attach_workspace:
          at: build/distributions
      - restore_cache:
          keys:
            - v1-yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v1-yarn-{{ .Branch }}-
            - v1-yarn-
      - setup_remote_docker
      - run:
          name: pip deps
          command: pip3 install -r requirements.txt
      - run:
          name: deploy
          command: sls deploy

  prod-deploy:
    environment:
      PROJECT: cloudkeeper-metrics-service
    working_directory: ~/repo
    docker:
      - image: ayankovsky/node-serverless-aws
    steps:
      - checkout
      - attach_workspace:
          at: build/distributions
      - restore_cache:
          keys:
            - v1-yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v1-yarn-{{ .Branch }}-
            - v1-yarn-
      - setup_remote_docker
      - run:
          name: pip deps
          command: pip3 install -r requirements.txt
      - run:
          name: deploy
          command: sls deploy --stage prod

workflows:
  version: 2
  build-and-deploy-dev:
    jobs:
      - ensure-deps
      - dev-deploy:
          filters:
            branches:
              only:
                - master
          context: ayankovsky-context
          requires:
            - ensure-deps

  build-and-deploy-prod:
    jobs:
      - ensure-deps:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^release.*/
      - prod-deploy:
          context: ayankovsky-context
          requires:
            - ensure-deps
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^release.*/
